### ISSUE TITLE
发现一个问题

### ISSUE THREAD

**Issue by zhangyuChen1991** [race604/WaveLoading#1]
在我手机上运行demo效果是这样的(华为荣耀6)
![b-img](https://cloud.githubusercontent.com/assets/16129428/21085842/691b4f00-c051-11e6-8b19-4ece89901d16.png)

**Comment by zhangyuChen1991** [comment]
画透明方框的代码没有起作用，底层灰色没显示出来。在oppo 5.1的系统上没有问题。

**Comment by race604** [comment]
Thank you very much for this issue.
I pushed a commit trying to fix this: 92e67f4. 
Because I don't have this device(华为荣耀6), @zhangyuChen1991 would you please test on your device, and check if it works?

**Comment by zhangyuChen1991** [comment]
已经OK了。不过能不能告诉我之前出错的原因呢，不甚感激！

**Comment by zhangyuChen1991** [comment]
我虽然找到了出错代码的位置，但是并不明白为什么在一些设备上它可以工作，在某些设备上就不行。期待有空能回复大概讲讲原因，谢谢哦

**Comment by race604** [comment]
Thank you, I'll mark this issue as fixed.

具体的原因是，某些机器的硬件加速优化，把画全透明的区域这样的代码给优化掉了，也就是你说的“画透明方框的代码没有起作用”。经过修改以后，通过 clipRect 来实现，这样性能可能还更高一些。
