### ISSUE TITLE
Indeterminate change issue

### ISSUE THREAD

**Issue by iamIcarus** [race604/WaveLoading#3]
When setting Indeterminate to true and then to false , setlevel does no work

**Comment by race604** [comment]
Thank you for report this bug. I have fixed it here.

**Comment by IAmDarush** [comment]
What are the min-max values for the setLevel? It doesn't seem to work for me whatever value I provide.

I am using **compile 'com.race604.waveloading:library:1.1.1'** .

Is there any way to decrease the animation time?

**Comment by race604** [comment]
1. About the `setLevel()` api, you can find the doc here: https://developer.android.com/reference/android/graphics/drawable/Drawable.html#setLevel(int)

2. The answer is yes. You can use this api `WaveLoading.setIndeterminateAnimator()` to set a custom Animator.
