### ISSUE TITLE
setLevel bug in Android 7.1.1

### ISSUE THREAD

**Issue by brzivoz** [race604/WaveLoading#4]
There are only two states of Drawable, completely empty and fully colored, even the smallest percent fills entire Drawable. It works perfectly on the same device running 6.0.1. Devices running 4.4 and 5.1 are also unaffected.
Thank you for this great library.

**Comment by race604** [comment]
I have test the demo on my Android 7.0 device and Emulator Android 7.1.1, it works fine.
Would you please provide more detail information about your device?

**Comment by brzivoz** [comment]
It is Xperia V running Ressurection rom. I will report behavior on Nexus 7 Flo running 7.1.

**Comment by race604** [comment]
Thank you, I appreciate that.

**Comment by brzivoz** [comment]
Doesn't work correctly on Nexus 7 Flo running 7.1 either (but works on 6.0.1).
```java
ImageView ivLoading = (ImageView) activity.findViewById(R.id.loading_image);
        mWaveDrawable = new WaveDrawable(activity, R.drawable.vector_logo);
        mWaveDrawable.setLevel(100); 
        mWaveDrawable.setWaveAmplitude(200);
        mWaveDrawable.setWaveLength(600);
        mWaveDrawable.setWaveSpeed(15);
        ivLoading.setImageDrawable(mWaveDrawable);
```

**Comment by brzivoz** [comment]
Ok, after revisiting project using this lib I've finally found out what is the culprit!
I have used vector drawable (xml) as a source image and it works as expected up to API 23, on later APIs it fills up drawable immediately. Bug is consistent using both AppCompatImageView and ImageView.
Only solution is to use raster image as a source.

Thank you again for this library.
